MasterDetails/MasterDetails/Controllers/SalesController.cs
using MasterDetails.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MasterDetails.Controllers
{
    public class SalesController : Controller
    {
        private MasterTiendaContext db = new MasterTiendaContext();
        // GET: Sales
        public ActionResult NewOrder()
        {
            OrderView orderview = new OrderView();
            orderview.Customer = new CustomerOrder();
            orderview.Products = new List<ProductOrder>();
            Session["OrderView"] = orderview;
            var list = db.Customers.ToList();
            ViewBag.Customerid = new SelectList(list,"Customerid","CompanyName");
            return View(orderview);
        }
        [HttpPost]
        public ActionResult NewOrder(OrderView orderview)
        {
            orderview = Session["OrderView"] as OrderView;
            int idcustomers = Convert.ToInt32(Request["Customerid"]);
            DateTime dateorder = Convert.ToDateTime(Request["Customer.Orderdate"]);
            Order neworder = new Order()
            {
                Customerid = idcustomers,
                OrderDate = dateorder
            };
            db.Orders.Add(neworder);
            db.SaveChanges();
            int lastorderid = db.Orders.ToList().Select(o => o.Orderid).Max();
            foreach(ProductOrder Item in orderview.Products)
            {
                var detail = new Orderdetail()
                {
                    Orderid = lastorderid,
                    Productid = Item.Productid,
                    Quantity = Item.quantity,
                    unitprice = Item.unitprice
                };
                db.Orderdetails.Add(detail);
            }
            db.SaveChanges();
            orderview = Session["OrderView"] as OrderView;
            var list = db.Customers.ToList();
            ViewBag.Customerid = new SelectList(list, "Customerid", "CompanyName");
            return View(orderview);
        }

        [HttpGet]
        public ActionResult AddProdut()
        {
            var listp = db.Products.ToList();
            ViewBag.Productid = new SelectList(listp, "Productid", "productname");
            return View();
        }

        [HttpPost]
        public ActionResult AddProdut(ProductOrder productorder)
        {
            var orderview = Session["OrderView"] as OrderView;
            var productid = Convert.ToInt32(Request["Productid"]);
            var product = db.Products.Find(productid);
            productorder = new ProductOrder()
            {
                Productid = product.Productid,
                productname = product.productname,
                unitprice = product.unitprice,
                quantity = Convert.ToInt32(Request["quantity"])
            };
            orderview.Products.Add(productorder);
            var list = db.Customers.ToList();
            ViewBag.Customerid = new SelectList(list, "Customerid", "CompanyName");
            var listp = db.Products.ToList();
            ViewBag.Productid = new SelectList(listp, "Productid", "productname");
            return View("NewOrder",orderview);
        }

        public ActionResult Edit( int? id)
        {
            var orderview = Session["OrderView"] as OrderView;
            var productid = new List<ProductOrder>();  
                        
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Productid,productname,unitprice,quatity")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                var orderview = Session["OrderView"] as OrderView;
                var productid = Convert.ToInt32(Request["Productid"]);
                var list = db.Customers.ToList();
                ViewBag.Customerid = new SelectList(list, "Customerid", "CompanyName");
                var listp = db.Products.ToList();
                ViewBag.Productid = new SelectList(listp, "Productid", "productname");
                return View("NewOrder", orderview);
            }
            return View(product);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var orderview = Session["OrderView"] as OrderView;
            var productid = Convert.ToInt32(Request["Productid"]);
            var list = db.Customers.ToList();
            ViewBag.Customerid = new SelectList(list, "Customerid", "CompanyName");
            var listp = db.Products.ToList();
            ViewBag.Productid = new SelectList(listp, "Productid", "productname");            
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("NewOrder", orderview);
        }
    }
}

MasterDetails/MasterDetails/Views/Sales/AddProdut.cshtml
@model MasterDetails.Models.ProductOrder
@{
    ViewBag.Title = "Agregar Productos";
}
<br /><br /><br />
<h2>Agregar Productos</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Detalles Ordenes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Productid, "Producto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Productid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Productid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar al Listado", "NewOrder")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MasterDetails/MasterDetails/Views/Sales/Delete.cshtml
@model MasterDetails.Models.Product

@{
    ViewBag.Title = "Eliminar";
}
<br /><br /><br />
<h2>Eliminar</h2>

<h3>¿Estás seguro que quieres eliminar esto?</h3>
<div>
    <h4>Orden de Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.productname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.unitprice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.unitprice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductOrder.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductOrder.quantity)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar a la Orden", "NewOrder")
        </div>
    }
</div>

MasterDetails/MasterDetails/Views/Sales/Edit.cshtml
@model MasterDetails.Models.Product

@{

                ViewBag.Title = "Editar";

}
<br /><br /><br />
<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Orden de producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Productid)

        <div class="form-group">
            @Html.LabelFor(model => model.productname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.unitprice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.unitprice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.unitprice, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ProductOrder.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductOrder.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductOrder.quantity, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la Orden", "NewOrder")
</div>

MasterDetails/MasterDetails/Views/Sales/NewOrder.cshtml
@model MasterDetails.Models.OrderView
@{
    ViewBag.Title = "Nueva Orden";
}
<link href="~/css/tabla.css" rel="stylesheet" />
<br /><br /><br />
<h2>Nueva Orden</h2>

@using (Html.BeginForm("NewOrder","Sales", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Orden</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Customer.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Customer.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Customer.Customerid, "Empresa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Customerid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Customer.Customerid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Agregar Producto", "AddProdut", new {  }, new { @class = "btn btn-default"})
                <input type="submit" value="Crear Orden" class="btn btn-default" />
            </div>
        </div>
    </div>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titles.productname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titles.quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titles.unitprice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titles.parcial)
            </th>
            <th></th>
        </tr>

        @for (int i=0;i<Model.Products.Count;i++)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.Products[i].productname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Products[i].quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Products[i].unitprice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Products[i].parcial)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = Model.Products[i].Productid }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = Model.Products[i].Productid })
            </td>
        </tr>
        }

    </table>
}


<div>
    @Html.ActionLink("Regresar a Inicio", "Index","Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}